### ISSUE TITLE
Stringing

### ISSUE THREAD

**Issue by sn-nti** [polishx3/Craftbot-Prusaslicer#2]
Hi
Really awesome taht you have made this profile for us to download.
i have now tried it with my Flow Idex XL and i get a of stringing.
im not use to Prusa Slicer,
i have tried to change the retraction speed to 60 as the default is in craftware pro but still to much stringing.

are you experiencing the same thing?

**Comment by polishx3** [comment]
thanks
new version will be out; default temp for generic PETG was too high

**Comment by sn-nti** [comment]
Nice. Thanks.

I was printing PLA, but i just noticed that i used the Prusament PLA profile and that was defaulted to 215C

**Comment by polishx3** [comment]
Typically if you use the the generic profile; the temp will be appropriately lower. Too high if a temp is a major cause for stringing.
