### ISSUE TITLE
M572 error,

### ISSUE THREAD

**Issue by Fisheye3D** [polishx3/Craftbot-Prusaslicer#3]
Love the profiles, When I have the Wipe tower activated I'm getting a M572 error in gcode, With it off its fine, Not sure why the wipe tower would have PA settings, Would adding some kind of gcode substitutions to replace M572 DO SO to nothing work?

![image](https://github.com/polishx3/Craftbot-Prusaslicer/assets/78997080/41875f1a-b609-4159-8085-7632fdda96d2)
 
![image](https://github.com/polishx3/Craftbot-Prusaslicer/assets/78997080/997438ac-0720-4d89-975e-61878c012ac6)

**Comment by polishx3** [comment]
Added with the latest updates to PrusaSlicer.
Unfortunately no PA on the craftbots; maybe later
Testing now to make sure substitutions don't break somethings else
should have update in couple days
thanks

**Comment by polishx3** [comment]
Uploaded 0.04, repaired
thanks
