### ISSUE TITLE
Bed size/offset incorrect? 

### ISSUE THREAD

**Issue by Fisheye3D** [polishx3/Craftbot-Prusaslicer#4]
![image](https://github.com/polishx3/Craftbot-Prusaslicer/assets/78997080/67527a27-2d16-4a63-a934-43fa19d1e948)
![image](https://github.com/polishx3/Craftbot-Prusaslicer/assets/78997080/542d6e5f-8717-4c8a-b7af-d10d65fbd600)
I think the bed size is incorrect, this is for left extruder only, shows in bed that its set to 425 with no offset,
![image](https://github.com/polishx3/Craftbot-Prusaslicer/assets/78997080/d1f8e9ab-18bd-4e81-bc8c-cb8c5c14ba35)

**Comment by polishx3** [comment]
Interesting craftware must have adjusted the print size in the new firmware, smaller print area.
Cause when I slice a large model in Craftware; their slicer. I get the same error.
Offset causes negative locations; which Craftbot Printer does not like.

**Comment by polishx3** [comment]
Om second thought it appears that 400 is max; will adjust

**Comment by Fisheye3D** [comment]
For this print i just changed it to the 386 listed on site. 
![image](https://github.com/polishx3/Craftbot-Prusaslicer/assets/78997080/506e56ab-9c98-470f-b1e0-bec9dfcf443a)

**Comment by polishx3** [comment]
what a mess; updated the sizes
thanks

**Comment by polishx3** [comment]
updated
