### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by ErrorindriveC** [polishx3/Craftbot-Prusaslicer#5]
Hi!
Thanks a lot for this profile. However, if i try to start a print a SyntaxError comes up (Line 48)
Could it be a problem with the E command in the gcode?

If i generate a gcode with the stock slicer it looks like this 
G1 X183.899 Y101.726 **E2.06103** ; Skirt

And with the Prusa Slicer like this
G1 X58.404 Y59.296 **E.12039**

[Gcode_STL.zip](https://github.com/polishx3/Craftbot-Prusaslicer/files/13201934/Gcode_STL.zip)

I hope you have time for my problem.
Thanks!

**Comment by polishx3** [comment]
Have been working; it's the lack of a 0 before the decimal. Will have to look closer. Thanks

**Comment by ErrorindriveC** [comment]
It's ok. It works. You already substitute the 0.
I just didn't use the right profile.

Thanks a lot for everything. The profile works perfectly.

01.11.2023 13:15:22 polishx3 ***@***.***>:
